Allocations, Deposits, updated Exchange endpoints
coinbase-samples/prime-explorer-js pull request #13
Opened 2023-01-26 20:20 UTC by jprix

2023-01-27 01:49 UTC, rcbgr requested changes
Please squash commits too

2023-01-27 01:49 UTC, rcbgr commented on src/UI/Orders/AllocationsList.svelte
> +     * Copyright 2022 Coinbase Global, Inc.
Add 2023 for new files

2023-01-27 01:49 UTC, rcbgr commented on src/UI/Orders/AllocationsList.svelte
> +    const startDate= getDate(new Date(), -6);
Space issue

2023-01-27 01:49 UTC, rcbgr commented on src/UI/Orders/AllocationsList.svelte
> +
Remove extra lines

2023-01-27 01:49 UTC, rcbgr commented on src/UI/UsersList.svelte
> +    href="https://commerce.coinbase.com/checkout/a5b2403c-94e4-446a-9f1b-822e2b4a8e42">
What is this UUID?

2023-01-27 01:49 UTC, rcbgr commented on src/UI/UsersList.svelte
> +  <a class="buy-with-crypto"
Why is commerce referenced?

2023-01-27 01:49 UTC, rcbgr commented on src/apis/Allocations.js
> + * Copyright 2022 Coinbase Global, Inc.
2023

2023-01-27 01:49 UTC, rcbgr commented on src/apis/Allocations.js
> +    queryParams ? queryParams : 'start_date=2022-06-05T00:00:01Z'
Does this date need to be dynamic?

2023-01-27 01:49 UTC, rcbgr commented on src/apis/Exchange/Currencies.js
>    const path = '/currencies';
Is path reference somewhere else? If not, just add the string to makeCall

2023-01-27 01:49 UTC, rcbgr commented on src/apis/Exchange/Deposits.js
> +//import { getAccounts } from '../../apis/Exchange/coinbase-accounts';
Remove unused code

2023-01-27 01:49 UTC, rcbgr commented on src/apis/Exchange/Withdrawals.js
> -  const path = `/withdrawals/coinbase-account`;
Should this be a single quote instead of a backtick?

2023-01-27 01:49 UTC, rcbgr commented on src/apis/Exchange/Withdrawals.js
> +  const path = `/withdrawals/coinbase-account/`;
Single quote?

2023-01-27 01:49 UTC, rcbgr commented on src/utils/constants.js
> +  date.setDate(1)
Why is this always 1?

2023-01-27 01:49 UTC, rcbgr commented on src/utils/constants.js
> +  date.setDate(Math.min(input.getDate(), getDaysInMonth(date.getFullYear(), date.getMonth()+1)))
What happens if the current month is December?

2023-01-31 21:37 UTC, jprix commented on src/UI/UsersList.svelte
> +  <a class="buy-with-crypto"
I was experimenting and forgot to remove.

2023-02-01 02:40 UTC, rcbgr reviewed
Files created in 2022 should be: 2022-present
Files created in 2023 should be: 2023-present

2023-02-01 16:23 UTC, jprix commented on src/UI/UsersList.svelte
> +    href="https://commerce.coinbase.com/checkout/a5b2403c-94e4-446a-9f1b-822e2b4a8e42">
removed commerce reference

2023-02-01 16:24 UTC, jprix commented on src/apis/Allocations.js
> +    queryParams ? queryParams : 'start_date=2022-06-05T00:00:01Z'
its a ternary, the user can pass in a dynamic date but they enter nothing in the filter form, i use that date

2023-02-01 16:25 UTC, jprix commented on src/apis/Exchange/Currencies.js
>    const path = '/currencies';
it is, used  as a method param on line 11 to make the function call

2023-02-03 22:50 UTC, rcbgr approved these changes
LGTM

2023-02-06 19:50 UTC, jprix commented on src/utils/constants.js
> +  date.setDate(1)
removed line 6.  not needed.

2023-02-06 19:54 UTC, nmorgancb approved these changes

2023-02-06 19:57 UTC, merged

2023-02-06 21:41 UTC, cfluke-cb approved these changes