typo in ternary date
coinbase-samples/prime-explorer-js pull request #14
Opened 2023-02-06 20:36 UTC by jprix

fat finger error.  fixing default filter date

2023-02-15 16:43 UTC, rcbgr requested changes

2023-02-15 16:43 UTC, rcbgr commented on src/apis/Allocations.js
> -    queryParams ? queryParams : 'start_date=2022-present-01-05T00:00:01Z'
Is this right? Looks like a search and replace error

2023-02-15 17:22 UTC, jprix commented on src/apis/Allocations.js
> -    queryParams ? queryParams : 'start_date=2022-present-01-05T00:00:01Z'
thats right.  its saying if there is no queryParams entered by the form, start from this date.

2023-02-15 21:55 UTC, rcbgr approved these changes
LGTM

2023-02-16 14:59 UTC, cfluke-cb approved these changes

2023-02-16 15:11 UTC, merged