March 2023
coinbase-samples/prime-explorer-js pull request #17
Opened 2023-04-25 17:53 UTC by jprix

updated tail wind and yaml versions
added:  create Allocation builder, viewing Allocations by Id
bunch of minor code optimizations and improvements.

2023-04-25 23:34 UTC, rcbgr requested changes

2023-04-25 23:34 UTC, rcbgr commented on src/UI/Orders/ListOrders.svelte
> +  // const updateOrders = async () => {
Remove unused code?

2023-04-25 23:34 UTC, rcbgr commented on src/UI/Orders/ListOrders.svelte
> +     const stringifiedQueryParams = generateQueryparams(queryParams);
Fix indention

2023-04-25 23:34 UTC, rcbgr commented on src/apis/Allocations.js
> +    queryParams ? queryParams : 'start_date=2023-04-05T00:00:01Z'
Should this be now - N months?

2023-04-25 23:34 UTC, rcbgr commented on src/apis/Exchange/Orders.js
> +  const path = "/orders/9a5cd33b-e371-4ff0-a7f1-5804250e38cc";
What are these portfolio ids? Make an env var?

2023-04-25 23:34 UTC, rcbgr commented on src/apis/Orders.js
> +    queryParams ? queryParams : 'start_date=2023-03-05T00:00:01Z'
Change to now - N months?

2023-04-25 23:34 UTC, rcbgr commented on src/routes/Orders/CreateAllocation.svelte
> +  // onMount(async () => {
Remove unused code

2023-04-25 23:34 UTC, rcbgr commented on src/routes/Orders/CreateAllocation.svelte
> +  //72 hours time cap
What does this mean?

2023-04-25 23:34 UTC, rcbgr commented on src/routes/Orders/CreateAllocation.svelte
> +   const queryParams=  {
Formatting is off

2023-04-25 23:34 UTC, rcbgr commented on tailwind.config.js
> +    // ...
Remove empty comment

2023-04-26 02:10 UTC, jprix commented on src/apis/Allocations.js
> +    queryParams ? queryParams : 'start_date=2023-04-05T00:00:01Z'
fixed it to go back N # of days automatically.

2023-04-26 02:12 UTC, jprix commented on src/apis/Exchange/Orders.js
> +  const path = "/orders/9a5cd33b-e371-4ff0-a7f1-5804250e38cc";
i actually threw that in to test something for a customer today..  i just removed the code, its not needed for the app.

2023-04-26 02:17 UTC, jprix commented on src/routes/Orders/CreateAllocation.svelte
> +  //72 hours time cap
that was a note to myself.  you can only allocate orders < 72 hours old.

2023-05-01 18:03 UTC, cfluke-cb commented on src/utils/constants.js
> +  return `${year}-${month}-${day}T${hours}:${minutes}:${seconds}Z`;
why not use toISOString? 
let d = new Date()
d.toISOString()
'2023-05-01T18:01:42.026Z'

2023-05-01 18:06 UTC, cfluke-cb commented on src/routes/Orders/CreateAllocation.svelte
> +  <option value="BTC-USD">BTC-USD</option>
I would make this a constant array and share it other places this is used.

2023-05-01 18:07 UTC, cfluke-cb commented on src/routes/Orders/CreateAllocation.svelte
> +  <option value="BTC-USD">BTC-USD</option>
like on [PlaceExchangeOrder.svelte](https://github.com/coinbase-samples/prime-explorer-js/pull/17/files#diff-11de12c3afd38e5e64a5e2cab88491c51971018c1c34d0ec6f72d022793d83fa)

2023-05-01 18:08 UTC, cfluke-cb commented on src/routes/Exchange/Orders/ExchangeOrderId.svelte
> +  let date, user_id, product_id, side, type, status;
any reason to be mixing individual lines to init, vs commas?

2023-05-01 18:09 UTC, cfluke-cb commented on src/routes/Exchange/Orders/ExchangeOpenOrders.svelte
> +          <option>BTC-USD</option>
share array as constant

2023-05-01 18:10 UTC, cfluke-cb commented on src/routes/Exchange/Orders/ExchangeFills.svelte
> +        { key: 'id', value: 'Order Id' },
same copy/paste as [ExchangeOpenOrders.svelte](https://github.com/coinbase-samples/prime-explorer-js/pull/17/files#diff-0cc25b50b61b095b83d800bac8975075d9ab05781722180c882dd731c15e48df)

2023-05-01 18:11 UTC, cfluke-cb commented on src/UI/WalletBalance.svelte
> +<h4>Past Rewards Amout: {walletBalanceDetails?.balance.past_rewards_amount}</h4>
typo

2023-05-01 18:16 UTC, cfluke-cb commented on src/routes/Orders/CreateAllocation.svelte
> +</select>
have you run npm run lint and npm run format?

2023-05-01 20:45 UTC, jprix commented on src/routes/Orders/CreateAllocation.svelte
> +  <option value="BTC-USD">BTC-USD</option>
great point. was meaning to get around to that. done.

2023-05-01 21:17 UTC, cfluke-cb commented on src/utils/constants.js
> +  'OMG-USD',
omg got delisted

2023-05-01 21:30 UTC, jprix commented on src/utils/constants.js
> +  'CEL-USD',
that was auto-genned, i dont need em.

2023-05-01 22:53 UTC, rcbgr approved these changes
Please squash commits and then merge

2023-05-02 13:37 UTC, cfluke-cb approved these changes

2023-05-02 14:55 UTC, merged